### ISSUE TITLE
neuA.fta headers

### ISSUE THREAD

**Issue by motroy** [tseemann/legsta#12]
Hi @tseemann,

we found a discrepancy in the fta file for the neuA loci. Two header formats exist:

>neuA_xx
>neuAh_xx

was this intentional? may this affect the results (i.e. unassigned allele for this loci, etc)?

thanks,
Yair

**Comment by tseemann** [comment]
Sorry i missed this report while i was on long summer break.

I have checked my code and luckily it does NOT affect the results.
I only use the number in the FASTA ID - and just use the gene name from the `.tfa` filename itself.

You did a good job spotting that though - it could been a serious bug!

But I will fix it anyway.
