### ISSUE TITLE
ERROR: Could not find 'any2fasta'. Please install it and ensure it is in the PATH.

### ISSUE THREAD

**Issue by tbazilegith** [tseemann/legsta#18]
Hi Seemann,
I got the is after I cloned the repository and rand this command

 ../bin/legsta *.fna *.gbk  (while in the test directory)

ERROR: Could not find 'any2fasta'. Please install it and ensure it is in the PATH.
which path?
Any ideas?
Thanks1
TJ

**Comment by tbazilegith** [comment]
I installed any2fasta and got it in the path, but
got this now
Found 'isPcr' =>USER/legsta/bin/isPcr
ERROR: Can not run isPcr
any ideas?
Thanks!

**Comment by tbazilegith** [comment]
Figured it out
No worries!

**Comment by tseemann** [comment]
Glad you got it sorted @tbazilegith 

The `conda` method is the best, it will install all the dependneces for you.
